### ISSUE TITLE
Referencing mutable fields in refinements

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/RefScript#100]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/immutable-field.ts

**Comment by panagosg7** [comment]
@bmcfluff This should NOT work, right? Just the version with an Immutable 'size' field.

**Comment by bmcfluff** [comment]
This one could go either way; I think we decided that there's no reason why you should want to do this without labeling it Immutable so it's ok if we return UNSAFE. The reason this is an Issue is because right now it returns CRASH (FixConstraint.BadConstraint(_)).

**Comment by bmcfluff** [comment]
Addressed by #103
