### ISSUE TITLE
Alias + this

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/refscript#104]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/alias.ts

Easy workaround is to avoid using type aliases in such situations.

**Comment by panagosg7** [comment]
Working in this commit:

https://github.com/UCSD-PL/refscript/blob/48c5eef56a1aaba6efda0b1a585e46f9123109fc/tests/pos/typealias/talias-09.ts
