### ISSUE TITLE
Variable named "v"

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/refscript#105]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/v-name.ts

Easy workaround: don't name things "v".

**Comment by bmcfluff** [comment]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/v-name-01.ts

**Comment by panagosg7** [comment]
Seems to be working at 15ccd4ff8fc4d6447eb842bf6d5f1b283a74decf
