### ISSUE TITLE
Missing deadcast

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/RefScript#111]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/bug-ziptype-unsupported.ts

**Comment by panagosg7** [comment]
Is it important that we allow this coersion is should we just fail it?

**Comment by bmcfluff** [comment]
I think it's important - is this test more convincing?

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/bug-ziptype-unsupported-02.ts

**Comment by panagosg7** [comment]
Addressed by https://github.com/UCSD-PL/RefScript/commit/5849c94b86257c4dfb80a0acefb3826c6309881c
