### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by lazywithclass** [UCSD-PL/refscript#146]
When navigating to http://goto.ucsd.edu/~pvekris/refscript I am redirected to http://goto.ucsd.edu:3003/, which errors as there doesn't seem to be a service running on that port.

**Comment by panagosg7** [comment]
Hi @lazywithclass! Thanks for your interest in refscript! I rebuilt and restarted the server that hosted the demo, so it should be available in the link you shared above.

Note, however, that this project has not been maintained for at least two years.

**Comment by lazywithclass** [comment]
Yes, I've seen the last commit is quite old, I'm going through the source to learn how you achieved refinements types.

Thanks a lot for keeping the server up and running even if you're not actively working on the project.
Just out of curiosity, did you stop working on refinement types for TypeScript or there's a more up to date repo with your work?

**Comment by ranjitjhala** [comment]
RefScript was @panagosg7 's Ph.D dissertation work, but he has since graduated and gone on to other fun projects ;-)

**Comment by lazywithclass** [comment]
@ranjitjhala I see. By the way, I've much appreciated [this video](https://www.youtube.com/watch?v=OEdXcn1rx6k) and [this other video](https://www.youtube.com/watch?v=8DBjDwKI138) you made! :D
