### ISSUE TITLE
Slow startup due to tsc?

### ISSUE THREAD

**Issue by ranjitjhala** [UCSD-PL/RefScript#27]
Why things are taking so long. e.g.

    time rsc tests/pos/simple/error.ts

    5.62 real         5.40 user         0.16 sys

The actual body of the file is just

    throw new Error("");

And so, the time in `fixpoint` is instantaneous.

This is not the biggest issue but worth looking into at some point...

**Comment by panagosg7** [comment]
Closing as most syb calls have been eliminated
