### ISSUE TITLE
Add support for names beginning in _

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/RefScript#49]
See:

https://github.com/UCSD-PL/RefScript/blob/underscore-var/tests/pos/misc/underscore-00.ts

Note that in other contexts _ seems to work fine:

https://github.com/UCSD-PL/RefScript/blob/underscore-var/tests/pos/misc/underscore-01.ts

**Comment by bmcfluff** [comment]
See https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/underscore-02.ts

**Comment by panagosg7** [comment]
Fixed by 

https://github.com/UCSD-PL/RefScript/commit/9f4a2ff05864e621850e8f380c1727e670d68578

Closing again
