### ISSUE TITLE
Add support for arguments named "func" or "obj"

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/RefScript#51]
See:

https://github.com/UCSD-PL/RefScript/blob/func-arg/tests/pos/misc/func-arg.ts

(can also rename arguments as a workaround)

**Comment by panagosg7** [comment]
This is reported as error as of: https://github.com/UCSD-PL/RefScript/commit/ada9793245dfb45cb6d3e21af1d0bc05443c9267

closing
