### ISSUE TITLE
Non-linear arithmetic

### ISSUE THREAD

**Issue by bmcfluff** [UCSD-PL/RefScript#91]
See:

https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/non-linear.ts

**Comment by ranjitjhala** [comment]
Thanks Ben! This

  http://rise4fun.com/Z3/xopl3

gives me cause for optimism. I can't duplicate that
on my own machine yet, perhaps due to some z3 parameter
trickery, but nevertheless there is hope.



On Thu, Jan 15, 2015 at 9:38 AM, bmcfluff <notifications@github.com> wrote:

> See:
>
> https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/non-linear.ts
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/issues/91>.
>



-- 
Ranjit.

**Comment by ranjitjhala** [comment]
See the branch "real" -- but we need a way to pass runtime options...

**Comment by panagosg7** [comment]
I just pushed a mechanism to add options:
```
/*@  option <OPTION SECTION> */ 
```
Whatever is in <OPTION SECTION> will be parsed as string.

You may want to change:
https://github.com/UCSD-PL/RefScript/blob/master/src/Language/Nano/Program.hs#L122
and:
https://github.com/UCSD-PL/RefScript/blob/master/src/Language/Nano/Typecheck/Parse.hs#L137

**Comment by ranjitjhala** [comment]
so where will I see this in the Nano world?

On Fri, Jan 16, 2015 at 3:57 PM, Panagiotis Vekris <notifications@github.com
> wrote:

> I just pushed a mechanism to add options:
>
> /*@  option <OPTION SECTION> */
>
> Whatever is in will be parsed as string.
>
> You may want to change:
>
> https://github.com/UCSD-PL/RefScript/blob/master/src/Language/Nano/Program.hs#L122
> and:
>
> https://github.com/UCSD-PL/RefScript/blob/master/src/Language/Nano/Typecheck/Parse.hs#L137
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/issues/91#issuecomment-70342018>.
>



-- 
Ranjit.

**Comment by panagosg7** [comment]
It's part of the program:
https://github.com/UCSD-PL/RefScript/blob/master/src/Language/Nano/Program.hs#L122

**Comment by ranjitjhala** [comment]
Got it thanks!

**Comment by panagosg7** [comment]
This seems to be supported now. Closing.
