### ISSUE TITLE
Primitive BitVector support

### ISSUE THREAD

**Issue by panagosg7** [UCSD-PL/RefScript#92]
Examples:
https://github.com/UCSD-PL/RefScript/blob/master/tests/pos/simple/bitVector.ts
https://github.com/UCSD-PL/RefScript/blob/master/tests/neg/simple/bitVector.ts
Are working already but with manual manipulation of bitvectors.

Also:
https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/features/bitVector.ts
Is not working yet, because we haven't encoded axioms like:
```
 a non-zero number has at least one bit non-zero
```
or
```
A & B has at most as many 1s as A or B has
```
and so on

**Comment by ranjitjhala** [comment]
@panagosg7 can you point me to the code that uses these "axioms".
meaning what concrete operators are used to arrive at the above facts?
In general I'd like to know what set of operators to support -- hex literals, 
bitwise-and/or/not, and what else? shifts?

**Comment by panagosg7** [comment]
Hex literals would be nice, cause right now we need to manually translate to dec.

Besides the rest of the operators you mention, there needs to be an interface between boolean operators and logical predicates. Most of the use cases depend on truthy-checks on the result of bitwise-AND.

In the simple case the "mask" only contains a single `1` and all the other positions are `0`.
This is the case of this example:
https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/features/bitVector.ts
```
if (symbol.flags & SymbolFlags.Transient) { ... }
```
`SymbolFlags.Transient`  has a single `1` at position `i_trans`.

So starting off with the premise:
```
bv_set(symbol.flags, i_trans) => extends_interface(symbol, Transient) 
```
We'd like to prove that in the then-branch of the conditional, bit `i_trans` of `symbol.flags` will be set.

A relevant axiom here would be:
```
∀ a b i . (bv_set(a,i) /\ (∀j, i≠j . not bv_set(a,j)) => truthy(a & b) => bv_set(b,i))
```
To get this to work, I have changed the check to:
```
if (symbol.flags & SymbolFlags.Transient === SymbolFlags.Transient) { ... }
```
Some more involved cases include premises like:
```
bv_set(a.flag, i) => extends_interface(a, Addition)
bv_set(a.flag, j) => extends_interface(a, Mulitplication)
```
And arrive at conclusions like: 
```
bv_set(a.flag, i | j) => extends_interface(a, Addition) || extends_interface(a, Mulitplication)
```

**Comment by ranjitjhala** [comment]
OK, lets discuss at noon.

On Fri, Jan 23, 2015 at 10:57 AM, Panagiotis Vekris <
notifications@github.com> wrote:

> Hex literals would be nice, cause right now we need to manually translate
> to dec.
>
> Besides the rest of the operators you mention, there needs to be an
> interface between boolean operators and logical predicates. Most of the use
> cases depend on truthy-checks on the result of bitwise-AND.
>
> In the simple case the "mask" only contains a single 1 and all the other
> positions are 0.
> This is the case of this example:
>
> https://github.com/UCSD-PL/RefScript/blob/master/tests/todo/features/bitVector.ts
>
> if (symbol.flags & SymbolFlags.Transient) { ... }
>
> SymbolFlags.Transient has a single 1 at position i_trans.
>
> So starting off with the premise:
>
> bv_set(symbol.flags, i_trans) => extends_interface(symbol, Transient)
>
> We'd like to prove that in the then-branch of the conditional, bit i_trans
> of symbol.flags will be set.
>
> A relevant axiom here would be:
>
> ∀ a b i . (bv_set(a,i) /\ (∀j, i≠j . not bv_set(a,j)) => truthy(a & b) => bv_set(b,i))
>
> To get this to work, I have changed the check to:
>
> if (symbol.flags & SymbolFlags.Transient === SymbolFlags.Transient) { ... }
>
> Some more involved cases include premises like:
>
> bv_set(a.flag, i) => extends_interface(a, Addition)
> bv_set(a.flag, j) => extends_interface(a, Mulitplication)
>
> And arrive at conclusions like:
>
> bv_set(a.flag, i | j) => extends_interface(a, Addition) || extends_interface(a, Mulitplication)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UCSD-PL/RefScript/issues/92#issuecomment-71244950>.
>



-- 
Ranjit.
